[book]
authors = ["Ritoban Roy-Chowdhury"]
language = "en"
multilingual = false
src = "src"
title = "AP Language and Composition"

[output.html.fold]
enable = true

[preprocessor.pandoc-format]
command = "mdbook-pandoc-format"
